### ISSUE TITLE
Add ability to add custom text inside progress ring

### ISSUE THREAD

**Issue by Yash-Singh1** [taisuke-j/progress-ring-component#10]
Currently, only an internal percentage format is allowed inside the progress ring. There should be some way to specify custom text based on the current percent amount.

**Comment by taisuke-j** [comment]
Hi @Yash-Singh1 , can you give me an example of custom text you want to pass to the progress ring?

**Comment by Yash-Singh1** [comment]
Such as `Goals Completed: 55/78` or `Chance of rain: 80%`.

**Comment by taisuke-j** [comment]
I see, thanks @Yash-Singh1  . By looking at the downloads on npm, yeah seems like people are starting to use this component. I would like to hear more use cases/opinions before starting to add more features like this though.

Anyone else out there, any comments? Actually I am interested in how people are using it

**Comment by taisuke-j** [comment]
@Yash-Singh1 Spoke with my colleagues and got the same feedback. Will work on this :+1:

**Comment by taisuke-j** [comment]
After some consideration, I decided not to expand the library with this feature. It is because I feel we should keep it simple and modular. If I'm having custom text that contains percentage/counts etc, I would probably do it as a separate component. For example, you could easily create custom animated text using this [animation library](https://www.npmjs.com/package/easing-animation-frames), which is internally used by this component library (The component library gets animated by the callback of the animation library).

Or you can go with other libraries that offer custom text like this one:

https://www.npmjs.com/package/react-circular-progressbar

**Comment by taisuke-j** [comment]
@Yash-Singh1 Just published the change. You can now use custom html in the component.

https://www.npmjs.com/package/progress-ring-component/v/1.0.9

**Comment by taisuke-j** [comment]
@Yash-Singh1 Now we have callback functions available

https://www.npmjs.com/package/progress-ring-component/v/1.0.14

Next step is to add color scheme options
